version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ac_fatesg_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: ac_fatesg_back
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Frontend React (Vite)
  frontend:
    build: ./frontend
    container_name: ac_fatesg_front
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que o volume sobrescreva os pacotes instalados no container
    ports:
      - "5173:5173"
    stdin_open: true # Necessário para o modo interativo do Vite
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: