"""tabela de processo criada e relacionamento com aluno adicionado

Revision ID: 0e0dbbe6c098
Revises: 3904c3444f21
Create Date: 2026-04-14 16:46:34.824073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e0dbbe6c098'
down_revision: Union[str, Sequence[str], None] = '3904c3444f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turma', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('data_ingresso', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_curso_id'), 'alunos', ['curso_id'], unique=False)
    op.create_index(op.f('ix_alunos_matricula'), 'alunos', ['matricula'], unique=True)
    op.create_table('coordenadores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordenadores_curso_id'), 'coordenadores', ['curso_id'], unique=False)
    op.create_index(op.f('ix_coordenadores_user_id'), 'coordenadores', ['user_id'], unique=False)
    op.create_table('processos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('coordenador_id_validador', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO_VALIDACAO', 'VALIDACAO_CONCLUIDA', 'INTEGRALIZADO', 'REJEITADO', name='statusprocessoenum'), nullable=False),
    sa.Column('horas_cumpridas', sa.Integer(), nullable=False),
    sa.Column('modalidades_atendidas', sa.Integer(), nullable=False),
    sa.Column('parecer_coordenador', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_validacao', sa.DateTime(), nullable=True),
    sa.Column('data_integralizacao', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['coordenador_id_validador'], ['coordenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processos_aluno_id'), 'processos', ['aluno_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processos_aluno_id'), table_name='processos')
    op.drop_table('processos')
    op.drop_index(op.f('ix_coordenadores_user_id'), table_name='coordenadores')
    op.drop_index(op.f('ix_coordenadores_curso_id'), table_name='coordenadores')
    op.drop_table('coordenadores')
    op.drop_index(op.f('ix_alunos_matricula'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_curso_id'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
