"""Criando tabelas de Usuario, Curso e Atividade

Revision ID: 206dcb73fbee
Revises: 
Create Date: 2026-04-14 12:03:57.544981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '206dcb73fbee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modalidade', sa.Enum('Ensino', 'Pesquisa', 'Extensao', 'Cultural', name='modalidadeenum'), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carga_horaria_equivalente', sa.Integer(), nullable=False),
    sa.Column('limite_anual', sa.Integer(), nullable=True),
    sa.Column('limite_total', sa.Integer(), nullable=True),
    sa.Column('limite_por_semestre', sa.Integer(), nullable=True),
    sa.Column('tipo_documentacao', sa.Enum('Certificado', 'Declaracao', 'Historico', 'Lista', 'Comprovante', name='tipodocumentoenum'), nullable=False),
    sa.Column('obs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_mec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carga_horaria_ac_obrigatoria', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_nome'), 'cursos', ['nome'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('funcao', sa.Enum('admin', 'secretaria', 'coordenador', name='funcaoenum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_cursos_nome'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_table('atividades')
    # ### end Alembic commands ###
